plugins {
    id("org.jetbrains.kotlin.jvm")
    `maven-publish`
    signing
    id("org.jetbrains.dokka")
}

group = "io.oira"
version = findProperty("projectVersion")?.toString() ?: "1.0.0"

java {
    withSourcesJar()
    withJavadocJar() // generates javadocJar task automatically
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = "fluxeco-api"
            from(components["java"])

            // attach artifacts generated by withSourcesJar() and withJavadocJar()
            artifact(tasks.named("sourcesJar"))
            artifact(tasks.named("javadocJar"))

            pom {
                name.set("FluxEco API")
                description.set("FluxEco API (proprietary) — API module for the FluxEco plugin")
                url.set("https://oira.io/fluxeco")

                licenses {
                    license {
                        name.set("Proprietary")
                        url.set("https://oira.io/fluxeco")
                    }
                }

                developers {
                    developer {
                        id.set("harfull")
                        name.set("Harfull")
                        email.set("harfull@oira.io")
                    }
                }

                scm {
                    connection.set("scm:git:https://oira.io/fluxeco")
                    developerConnection.set("scm:git:https://oira.io/fluxeco")
                    url.set("https://oira.io/fluxeco")
                }
            }
        }
    }
}

signing {
    val signingKey: String? by project
    val signingPassword: String? by project

    if (!signingKey.isNullOrEmpty() && !signingPassword.isNullOrEmpty()) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign(publishing.publications["mavenJava"])
    }
}
